#!/usr/bin/env python3
"""Keep Rustty's transition table and UTF-8 DFA aligned with the Zig reference."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]


def camel(value):
    return "".join(part.title() for part in value.split("_"))


def generate():
    source = (ROOT / "src/terminal/parse_table.zig").read_text()
    body = source.split("// anywhere transitions", 1)[1].split("// Create our immutable version", 1)[0]
    lines = ["// Generated by test/rustty/generate-parser.py; do not edit.",
             "use super::{State, TransitionAction};", "use State::*;", "use TransitionAction::*;",
             "pub(super) const TABLE: [[(State, TransitionAction); 14]; 256] = build();",
             "const fn build() -> [[(State, TransitionAction); 14]; 256] {",
             "let mut table = [[(Ground, None); 14]; 256];",
             "let states = [Ground, Escape, EscapeIntermediate, CsiEntry, CsiIntermediate, CsiParam, CsiIgnore, DcsEntry, DcsParam, DcsIntermediate, DcsPassthrough, DcsIgnore, OscString, SosPmApcString];",
             "let mut s = 0; while s < 14 { let mut c = 0; while c < 256 { table[c][s] = (states[s], None); c += 1; } s += 1; }",
             "let mut s = 0; while s < 14 { let source = states[s];"]
    in_anywhere = True
    for line in body.splitlines():
        if line.strip() == "// ground":
            lines.append("s += 1; }")
            in_anywhere = False
        match = re.search(r"const source = State\.(\w+);", line)
        if match:
            lines.append(f"let source = {camel(match[1])};")
        match = re.search(r"(single|range)\(&result, ([^;]+)\);", line)
        if not match or line.lstrip().startswith("//"):
            continue
        args = [v.strip() for v in match[2].split(",")]
        if match[1] == "single":
            args.insert(1, args[0])
        start, end, before, after, action = args
        before = camel(before[1:]) if before.startswith(".") else before
        after = camel(after[1:]) if after.startswith(".") else after
        lines.append(f"set(&mut table, {start}, {end}, {before}, {after}, {camel(action[1:])});")
    assert not in_anywhere
    lines += ["table", "}",
              "const fn set(table: &mut [[(State, TransitionAction); 14]; 256], start: usize, end: usize, before: State, after: State, action: TransitionAction) {",
              "let mut c = start; while c <= end { table[c][before as usize] = (after, action); c += 1; }", "}"]
    utf = (ROOT / "src/terminal/UTF8Decoder.zig").read_text()
    for zig_name, rust_name in [("char_classes", "UTF8_CLASSES"), ("transitions", "UTF8_TRANSITIONS")]:
        raw = re.search(rf"const {zig_name} = \[_\]u\d+\s*\{{(.*?)\}};", utf, re.S)[1]
        values = re.findall(r"\d+", raw)
        lines.append(f"pub(super) const {rust_name}: [u8; {len(values)}] = [{','.join(values)}];")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "crates/rustty-parser/src/table.rs"
    generated = generate()
    # rustfmt is deliberately not used: the source stays deterministic and
    # independent of which Rust toolchain regenerates the reference table.
    if args.check:
        if target.read_text() != generated:
            raise SystemExit("Rustty parser tables differ; run test/rustty/generate-parser.py")
    else:
        target.write_text(generated)
