#!/usr/bin/env python3
"""Generate pure Rust XTGETTCAP data from Ghostty's checked-in terminfo source."""
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parents[3]
source = (root / "src/terminfo/ghostty.zig").read_text()
entries = re.findall(
    r'\.\{\s*\.name\s*=\s*"([^"\\]+)"\s*,\s*\.value\s*=\s*\.\{\s*'
    r'\.(boolean|numeric|string)\s*=\s*(\{\}|\d+|"(?:[^"\\]|\\.)*")\s*\}\s*\}',
    source,
)
assert len(entries) == len(re.findall(r'\.name\s*=', source)), "unsupported terminfo syntax"
values = {"Co": "256", "RGB": "8"}
for name, kind, raw in entries:
    value = "" if kind == "boolean" else raw if kind == "numeric" else json.loads(raw)
    if kind == "string" and "%" not in value:
        value = value.replace(r"\E", "\x1b")
        while "^" in value:
            index = value.index("^")
            assert index == 0, "new control notation requires review"
            char = value[1]
            value = chr(127 if char == "?" else ord(char) - 64) + value[2:]
    values[name] = value

lines = [
    "// Generated by crates/rustty-vt/tools/generate-terminfo.py; do not edit.",
    "// Source: src/terminfo/ghostty.zig. TN is supplied by the host separately.",
    "#[rustfmt::skip]",
    "pub(crate) const CAPABILITIES: &[(&str, &str)] = &[",
]
for key, value in sorted((key.encode().hex().upper(), value.encode().hex().upper()) for key, value in values.items()):
    lines.append(f'    ("{key}", "{value}"),')
lines.append("];")
(root / "crates/rustty-vt/src/terminfo.rs").write_text("\n".join(lines) + "\n")
